#!/bin/bash
### create virtual environment
python -m venv venv

### 
venv\Scripts\activate.bat
python -m ensurepip --upgrade
python -m pip install --upgrade pip
python -m pip install zxcvbn-python
python -m pip install flask 
python -m pip install python-Levenshtein
python -m pip install requests
pip install flask-limiter

# python -m pip install argon2 # ment for future password hashing
### launch the app
python app.py